name: Post welcome comment
on:
   pull_request:
     types: [opened]
jobs:
  build:
    name: Post welcome comment
    runs-on: ubuntu-latest
    steps:
      - run: gh pr comment $PR_URL --body "Hello, thank you for contributing to this innovative project helping people to reunite with their lost items! Sit tight while your pull request is being apporoved!"
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
